/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaysRouteImport } from './routes/_authenticated.stays'
import { Route as AuthenticatedHotelsRouteImport } from './routes/_authenticated.hotels'
import { Route as AuthenticatedEmailLogRouteImport } from './routes/_authenticated.email-log'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated.bookings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaysRoute = AuthenticatedStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHotelsRoute = AuthenticatedHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailLogRoute = AuthenticatedEmailLogRouteImport.update({
  id: '/email-log',
  path: '/email-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/email-log': typeof AuthenticatedEmailLogRoute
  '/hotels': typeof AuthenticatedHotelsRoute
  '/stays': typeof AuthenticatedStaysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/email-log': typeof AuthenticatedEmailLogRoute
  '/hotels': typeof AuthenticatedHotelsRoute
  '/stays': typeof AuthenticatedStaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/email-log': typeof AuthenticatedEmailLogRoute
  '/_authenticated/hotels': typeof AuthenticatedHotelsRoute
  '/_authenticated/stays': typeof AuthenticatedStaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookings'
    | '/companies'
    | '/contacts'
    | '/documents'
    | '/email-log'
    | '/hotels'
    | '/stays'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bookings'
    | '/companies'
    | '/contacts'
    | '/documents'
    | '/email-log'
    | '/hotels'
    | '/stays'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/bookings'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/documents'
    | '/_authenticated/email-log'
    | '/_authenticated/hotels'
    | '/_authenticated/stays'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stays': {
      id: '/_authenticated/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof AuthenticatedStaysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hotels': {
      id: '/_authenticated/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof AuthenticatedHotelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-log': {
      id: '/_authenticated/email-log'
      path: '/email-log'
      fullPath: '/email-log'
      preLoaderRoute: typeof AuthenticatedEmailLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmailLogRoute: typeof AuthenticatedEmailLogRoute
  AuthenticatedHotelsRoute: typeof AuthenticatedHotelsRoute
  AuthenticatedStaysRoute: typeof AuthenticatedStaysRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmailLogRoute: AuthenticatedEmailLogRoute,
  AuthenticatedHotelsRoute: AuthenticatedHotelsRoute,
  AuthenticatedStaysRoute: AuthenticatedStaysRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
